server:
  port: 9094
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Mysql@143
    url: jdbc:mysql://localhost:3306/NewDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  
  mail:
    host: smtp.gmail.com
    password: 9533237760
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: "sureshkumarreddyraina143@gmail.com\t"
    
forgotpassword-app:
 messages:
  forgotPwdMailSubject: Forgot Password 
  forgotPwdBodyMailTemplate: FORGOT-PWD-EMAIL-BODY-Template.txt
  Invalidemail: No Record Found with given email
  passwordsent: Password sent to registered email
  error: Internal Server Error
   
       